/*
 * Copyright (C) 2013 Lucien Xu <sfietkonstantin@free.fr>
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this library; see the file COPYING.LIB.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 */

// This class is autogenerated using themehelper.py
// Any modification done in this file will be overridden

#include "nemothemecheckbox.h"

NemoThemeCheckbox::NemoThemeCheckbox(QObject *parent)
    : QObject(parent)
{
}

QColor NemoThemeCheckbox::back1() const
{
    return m_back1;
}

void NemoThemeCheckbox::setBack1(const QColor &back1)
{
    if (m_back1 != back1) {
        m_back1 = back1;
        emit back1Changed();
    }
}

QColor NemoThemeCheckbox::back2() const
{
    return m_back2;
}

void NemoThemeCheckbox::setBack2(const QColor &back2)
{
    if (m_back2 != back2) {
        m_back2 = back2;
        emit back2Changed();
    }
}
